### ISSUE TITLE
Second image was not provided! in .slap

### ISSUE THREAD

**Issue by EG-M** [DevSnowflake/canvacord#55]
Hi snowflake,

I have an error in your pkg's slap function
the code: 
```
const Discord = require('discord.js');
const { MessageEmbed } = require("discord.js");
const { Default_Prefix, Color, Support, Donate } = require("../../config.js");
const canvacord = require("canvacord")

module.exports = {
  name: "test",
  aliases: [],
  category: "Fun",
  description: "Fake phub comment.",
  usage: "test @user",
  run: async (client, message, args, db) => {
const user = message.mentions.users.first()
const yt = await canvacord.Canvas.slap({"image1":message.author.displayAvatarURL({format: "png"}),"image2":message.author.displayAvatarURL({format: "png"})})

    let attachment = new Discord.MessageAttachment(yt, "test.png")
    message.channel.send(attachment)
  }
};
```

When i type test

I get this error

```
(node:1654) UnhandledPromiseRejectionWarning: Error: Second image was not provided!
    at Function.slap (/home/runner/ZealousNoteworthyDecagon/node_modules/canvacord/src/Canvacord.js:433:28)
    at Object.run (/home/runner/ZealousNoteworthyDecagon/commands/Fun/test.js:14:35)
    at Client.<anonymous> (/home/runner/ZealousNoteworthyDecagon/index.js:78:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1654) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1654) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Snowflake107** [comment]
it's `Canvas.slap(firstImage, secondImage)`

**Comment by EG-M** [comment]
> it's `Canvas.slap(firstImage, secondImage)`

you mean add links withour "image1": and etc?

**Comment by Snowflake107** [comment]
um yes
