### ISSUE TITLE
MomentJS Dependency Issue

### ISSUE THREAD

**Issue by Archreus** [DevSnowflake/canvacord#63]
I just installed Canvacord v5.0.8 and for a few minutes the rank system was working fine. But after I started to get this issue from one of the MomentJS files:

```
Unhandled promise rejection: TypeError: Function has non-object prototype 'undefined' in instanceof check
    at AsyncFunction.[Symbol.hasInstance] (<anonymous>)
    at isFunction (C:\Users\ascen\OneDrive\Documents\VoTech\node_modules\moment\moment.js:344:55)
    at addRegexToken (C:\Users\ascen\OneDrive\Documents\VoTech\node_modules\moment\moment.js:790:26)
    at C:\Users\ascen\OneDrive\Documents\VoTech\node_modules\moment\moment.js:925:5
    at C:\Users\ascen\OneDrive\Documents\VoTech\node_modules\moment\moment.js:8:85
    at Object.<anonymous> (C:\Users\ascen\OneDrive\Documents\VoTech\node_modules\moment\moment.js:11:2)
    at Module._compile (internal/modules/cjs/loader.js:1085:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:791:14)
```

I don't use MomentJS anywhere in my files. Apparently MomentJS is also required in Canvacord. I tried uninstalling Canvacord completely a few times, and reinstalling it, but I kept getting the same issue. I also tried rebuilding, but I still got the issue.

Apparently this issue occurs in this piece of code:
```js
    function isFunction(input) {
        return (
            (typeof Function !== 'undefined' && input instanceof Function) ||
            Object.prototype.toString.call(input) === '[object Function]'
        );
    }
```

The whole file in which throws the error: https://pastebin.com/ub76swT1

**Comment by Snowflake107** [comment]
I think this issue is resolved in `v5.1.0`. If you are still getting this error, feel free to re-open this issue.
