### ISSUE TITLE
Could not parse font file

### ISSUE THREAD

**Issue by ibnusyawall** [DevSnowflake/canvacord#67]
I don't know why, I want to run errors always, how do I fix that?

```sh
/root/node_modules/canvas/index.js:48
  return Canvas._registerFont(fs.realpathSync(src), fontFace)
                ^

Error: Could not parse font file
    at Object.registerFont (/root/node_modules/canvas/index.js:48:17)
    at Timeout._onTimeout (/root/node_modules/canvacord/src/Rank.js:175:24)
```

**Comment by meliooff** [comment]
Hi, how did you fix that ?
