### ISSUE TITLE
Code:7736) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'Rank' of undefined

### ISSUE THREAD

**Issue by YouBotwebsite** [DevSnowflake/canvacord#74]
When i do !rank then i get code:7736) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'Rank' of undefined

ode:7736) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'Rank' of undefined
    at Object.module.exports.run (C:\Users\Ryan-Gta\Desktop\Discord_Bot_YT\commands\level.js:16:44)
    at Client.<anonymous> (C:\Users\Ryan-Gta\Desktop\Discord_Bot_YT\index.js:255:28)
    at Client.emit (events.js:315:20)
    at MessageCreateAction.handle (C:\Users\Ryan-Gta\Desktop\Discord_Bot_YT\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\Ryan-Gta\Desktop\Discord_Bot_YT\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\Ryan-Gta\Desktop\Discord_Bot_YT\node_modules\discord.js\src\client\websocket\WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (C:\Users\Ryan-Gta\Desktop\Discord_Bot_YT\node_modules\discord.js\src\client\websocket\WebSocketShard.js:436:22)
    at WebSocketShard.onMessage (C:\Users\Ryan-Gta\Desktop\Discord_Bot_YT\node_modules\discord.js\src\client\websocket\WebSocketShard.js:293:10)
    at WebSocket.onMessage (C:\Users\Ryan-Gta\Desktop\Discord_Bot_YT\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:315:20)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7736) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7736) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by zyrouge** [comment]
Closing due to lack of context and inactivity. Feel free to open if needed.
