### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by sanzorez** [DevSnowflake/canvacord#94]
internal/modules/cjs/loader.js:1122
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: dlopen failed: library "/storage/emulated/0/selfsanz/node_modules/canvas/build/Release/canvas.node" needed or dlopened by "/data/data/com.termux/files/usr/bin/node" is not accessible for the namespace "(default)"
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/storage/emulated/0/selfsanz/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)

**Comment by Snowflake107** [comment]
https://github.com/Automattic/node-canvas/issues/1756

**Comment by sanzorez** [comment]
> [Automattic/node-canvas#1756](https://github.com/Automattic/node-canvas/issues/1756)

Ok
